{% set name = "safer" %}
{% set version = "4.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa6f4bff3606668fec6c6e88eb6757dd0b6ac017dbefe090f95e14495e160d56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - safer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rec/safer
  summary: 🧿 A safer writer for files and streams 🧿
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
