{% set name = "safer" %}
{% set version = "4.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/safer-{{ version }}.tar.gz
  sha256: c3279c01c951d9742421598daaf0173c669914ceecbb051ba94f016d8b43bfcb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - safer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rec/safer
  summary: 🧿 A safer writer for files and streams 🧿
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
