{% set name = "safer" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/safer-{{ version }}.tar.gz
  sha256: 291432798173bdf6211d288e9f0ef550d4345eddd8a2bc9dfc658cb1dea8a231

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - safer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rec/safer
  summary: 🧿 A safer writer for files and streams 🧿
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
