{% set name = "safer" %}
{% set version = "4.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee963640e593cd67e05c8992caecb71fdbfdc48ba1fdc3b295531c5998758205
  patches:
    - win-charmap-codec.patch

build:
  number: 0
  # cannot be noarch b/c it does not use entrypotins, just scripts :-/
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - safer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rec/safer
  summary: A safer file opener
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
