schema_version: 1

context:
  version: "6.0.4"

package:
  name: safer
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/safer/safer-${{ version }}.tar.gz
  sha256: bc1e540efd30c352288d1acf40648e0be826775dddbb4b6ef2b198ff2e1b482f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - safer
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: 🧿 A safer writer for files and streams 🧿
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rec/safer
  documentation: https://rec.github.io/safer

extra:
  recipe-maintainers:
    - ocefpaf
